"""
Auto-generated by TrainModelAgent  |  2026-05-31 00:20:22
Best model : xgboost
Features   : 96
Target     : TARGET
"""

import numpy as np
import pandas as pd
import joblib
from pathlib import Path

# ── Load artifact ─────────────────────────────────────────────────────────────
_ARTIFACT_PATH = Path(__file__).parent / "final_model.pkl"
_artifact      = joblib.load(_ARTIFACT_PATH)

model         = _artifact["model"]
feature_cols  = _artifact["feature_cols"]
cat_encoders  = _artifact["cat_encoders"]
target_column = _artifact["target_column"]

# ── Feature list (recorded at training time) ──────────────────────────────────
FEATURES = [
    "EXT_SOURCES_MEAN",
    "EXT2_EXT3",
    "EXT_SOURCES_PROD",
    "EXT_SOURCE_2",
    "EXT_SOURCE_3",
    "EXT_SOURCE_1",
    "CREDIT_GOODS_RATIO",
    "prev_CODE_REJECT_REASON_nunique",
    "REGION_RATING_CLIENT_W_CITY",
    "cc_CNT_DRAWINGS_CURRENT_std",
    "REGION_RATING_CLIENT",
    "ins_DAYS_INSTALMENT_min",
    "cc_CNT_DRAWINGS_CURRENT_max",
    "ins_DAYS_INSTALMENT_std",
    "ins_DAYS_ENTRY_PAYMENT_std",
    "NAME_EDUCATION_TYPE",
    "CODE_GENDER",
    "pos_MONTHS_BALANCE_std",
    "REG_CITY_NOT_WORK_CITY",
    "cc_AMT_BALANCE_mean",
    "cc_AMT_TOTAL_RECEIVABLE_mean",
    "cc_AMT_RECIVABLE_mean",
    "cc_AMT_RECEIVABLE_PRINCIPAL_mean",
    "bur_DAYS_CREDIT_max",
    "cc_CNT_DRAWINGS_CURRENT_mean",
    "prev_DAYS_FIRST_DRAWING_std",
    "NAME_INCOME_TYPE",
    "FLAG_EMP_PHONE",
    "bur_DAYS_CREDIT_ENDDATE_sum",
    "prev_DAYS_FIRST_DRAWING_min",
    "DAYS_EMPLOYED",
    "REG_CITY_NOT_LIVE_CITY",
    "FLAG_DOCUMENT_3",
    "bur_bb_MONTHS_BALANCE_count_mean",
    "cc_AMT_INST_MIN_REGULARITY_mean",
    "bur_bb_MONTHS_BALANCE_std_mean",
    "EMPLOYED_BIRTH_RATIO",
    "prev_CNT_PAYMENT_std",
    "cc_AMT_DRAWINGS_CURRENT_std",
    "cc_AMT_BALANCE_max",
    "AMT_GOODS_PRICE",
    "cc_AMT_TOTAL_RECEIVABLE_max",
    "cc_AMT_INST_MIN_REGULARITY_std",
    "prev_DAYS_FIRST_DRAWING_sum",
    "cc_AMT_RECEIVABLE_PRINCIPAL_max",
    "bur_bb_MONTHS_BALANCE_count_max",
    "cc_AMT_BALANCE_min",
    "cc_AMT_INST_MIN_REGULARITY_max",
    "bur_bb_MONTHS_BALANCE_std_max",
    "cc_AMT_RECEIVABLE_PRINCIPAL_min",
    "cc_AMT_DRAWINGS_CURRENT_mean",
    "cc_AMT_BALANCE_std",
    "cc_AMT_TOTAL_RECEIVABLE_std",
    "DEF_30_CNT_SOCIAL_CIRCLE",
    "SOCIAL_DEF_RATIO",
    "DEF_60_CNT_SOCIAL_CIRCLE",
    "NAME_CONTRACT_TYPE",
    "cc_CNT_DRAWINGS_CURRENT_sum",
    "cc_CNT_DRAWINGS_ATM_CURRENT_sum",
    "AMT_CREDIT",
    "prev_CNT_PAYMENT_max",
    "LIVINGAREA_AVG",
    "prev_DAYS_FIRST_DUE_count",
    "bur_DAYS_ENDDATE_FACT_std",
    "FLAG_WORK_PHONE",
    "prev_CNT_PAYMENT_sum",
    "prev_CNT_PAYMENT_mean",
    "pos_CNT_INSTALMENT_FUTURE_mean",
    "prev_AMT_DOWN_PAYMENT_sum",
    "bur_bb_MONTHS_BALANCE_count_min",
    "ins_AMT_PAYMENT_min",
    "bur_bb_MONTHS_BALANCE_std_min",
    "cc_AMT_DRAWINGS_ATM_CURRENT_sum",
    "prev_AMT_DOWN_PAYMENT_max",
    "cc_MONTHS_BALANCE_sum",
    "CAR_TO_BIRTH_RATIO",
    "ins_AMT_PAYMENT_sum",
    "FLAG_OWN_CAR",
    "cc_AMT_CREDIT_LIMIT_ACTUAL_sum",
    "cc_AMT_PAYMENT_TOTAL_CURRENT_max",
    "pos_CNT_INSTALMENT_FUTURE_std",
    "OWN_CAR_AGE",
    "bur_AMT_CREDIT_SUM_sum",
    "cc_AMT_PAYMENT_TOTAL_CURRENT_mean",
    "pos_CNT_INSTALMENT_FUTURE_max",
    "pos_CNT_INSTALMENT_max",
    "cc_AMT_DRAWINGS_ATM_CURRENT_count",
    "AMT_ANNUITY",
    "ANNUITY_CREDIT_RATIO",
    "prev_NFLAG_INSURED_ON_APPROVAL_min",
    "bur_AMT_CREDIT_SUM_LIMIT_max",
    "bur_AMT_CREDIT_SUM_LIMIT_mean",
    "bur_AMT_CREDIT_SUM_OVERDUE_sum",
    "bur_AMT_CREDIT_SUM_LIMIT_sum",
    "BUREAU_DEBT_INCOME_RATIO",
    "pos_SK_DPD_DEF_max"
]

# Categorical columns encoded via LabelEncoder
CAT_COLS = []

# Best hyperparameters
BEST_PARAMS = {
    "n_estimators": 750,
    "learning_rate": 0.010725209743171996,
    "max_depth": 10,
    "min_child_weight": 25,
    "subsample": 0.5274034664069657,
    "colsample_bytree": 0.5090949803242604,
    "gamma": 3.939402261362697e-07,
    "reg_alpha": 5.472429642032198e-06,
    "reg_lambda": 0.00052821153945323,
    "eval_metric": "logloss",
    "random_state": 42,
    "n_jobs": -1,
    "verbosity": 0
}


# ── Preprocessing ─────────────────────────────────────────────────────────────
def preprocess(df: pd.DataFrame) -> pd.DataFrame:
    """Apply the same encoding + imputation used during training."""
    avail = [c for c in FEATURES if c in df.columns]
    out = df[avail].copy()
    for col in out.columns:
        if col in cat_encoders:
            le    = cat_encoders[col]
            known = set(le.classes_)
            vals  = out[col].fillna("__NA__").astype(str)
            out[col] = le.transform(vals.apply(lambda x: x if x in known else "__NA__"))
        else:
            out[col] = out[col].fillna(-999)
    return out


# ── Prediction helpers ────────────────────────────────────────────────────────
def predict_proba(df: pd.DataFrame) -> np.ndarray:
    """Return probability of the positive class (shape: n_samples,)."""
    return model.predict_proba(preprocess(df))[:, 1]


def predict(df: pd.DataFrame, threshold: float = 0.5) -> np.ndarray:
    """Return binary predictions (0/1) at a given probability threshold."""
    return (predict_proba(df) >= threshold).astype(int)


# ── Example usage ─────────────────────────────────────────────────────────────
if __name__ == "__main__":
    sample = pd.read_csv(Path(__file__).parent / "engineered_data.csv")
    scores = predict_proba(sample)
    preds  = predict(sample, threshold=0.5)
    print(f"Rows scored   : {len(scores)}")
    print(f"Score range   : {scores.min():.4f} – {scores.max():.4f}")
    print(f"Positive rate : {preds.mean():.2%}")
    print(f"Sample scores : {scores[:5]}")
